name: complex_workflow

on:
  [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: date
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
    
  job_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: date 
    
  job_3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: date
    
  job_4:
    needs: [job_1, job_2, job_3]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: date
      
